---
create_containers: 4
default_container_name: docker
default_container_image: ubuntu
default_container_command: sleep 1d

elk_repo: 'https://github.com/gaomc66/elk-stack.git'


filebeat_version: 7.x
filebeat_create_config: true

filebeat_inputs:
  - type: log
    paths:
      - /dev/test.log
    encoding: utf-8

filebeat_output_elasticsearch_enabled: false
filebeat_output_elasticsearch_hosts:
  - "http://34.203.244.31:9200"

filebeat_output_logstash_enabled: true
filebeat_output_logstash_hosts:
  - "34.203.244.31:9600"

filebeat_enable_logging: true
filebeat_log_level: warning
filebeat_log_dir: /var/log/mybeat
filebeat_log_filename: mybeat.log

filebeat_ssl_dir: /etc/pki/logstash
filebeat_ssl_certificate_file: ""
filebeat_ssl_key_file: ""
filebeat_ssl_insecure: "false"